#!/bin/bash

# Get the absolute path of the current script's directory
current_script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Print the absolute path
echo "$current_script_dir"
